"""added len 16

Revision ID: 5e5a7a290aec
Revises: 
Create Date: 2023-08-19 19:43:15.485380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5a7a290aec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_map', sa.Column('lol', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_url_map_lol'), 'url_map', ['lol'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_map_lol'), table_name='url_map')
    op.drop_column('url_map', 'lol')
    # ### end Alembic commands ###
