"""added len 17

Revision ID: 78c5195da1e3
Revises: 5e5a7a290aec
Create Date: 2023-08-19 19:44:18.691801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c5195da1e3'
down_revision = '5e5a7a290aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_url_map_lol', table_name='url_map')
    op.drop_column('url_map', 'lol')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_map', sa.Column('lol', sa.DATETIME(), nullable=True))
    op.create_index('ix_url_map_lol', 'url_map', ['lol'], unique=False)
    # ### end Alembic commands ###
